### ISSUE TITLE
Handy CLI Apps 中是否应当保留 Homebrew badge

### ISSUE THREAD

**Issue by shirok1** [hitszlug/wiki#47]
https://github.com/hitszlug/wiki/blob/af670f2c3f37e6479acb4653642e3b729f2ed6b7/docs/linux-tricks/handy-cli-apps.md?plain=1#L17

我觉得大部分人并不会看了这个教程然后去装了个 brew……

PS：可以考虑换成 https://repology.org/project/tealdeer/badges 这种覆盖多个软件仓库的

[![Packaging status](https://repology.org/badge/tiny-repos/tealdeer.svg)](https://repology.org/project/tealdeer/versions)

**Comment by eastonman** [comment]
同意，homebrew可能不太合适

**Comment by shirok1** [comment]
#48
